syntax = "proto3";

package com.sentinelcodes.datapipeline.protobuf;

option java_package = "com.sentinelcodes.datapipeline.protobuf";
option java_outer_classname = "SwapEventProto";

message SwapEvent {
  string jsonrpc = 1;
  int32 id = 2;
  repeated RawLog result = 3;
}

message RawLog {
  string address = 1;
  string blockHash = 2;
  string blockNumber = 3;
  string data = 4;
  repeated string topics = 5;
  string transactionHash = 6;
  string transactionIndex = 7;
  string logIndex = 8;
  bool removed = 9;
  ExtractedData extractedData = 10 [json_name = "ExtractedData"];
}

message ExtractedData {
  // Using string to represent large numbers safely.
  string amount0 = 1;
  string amount1 = 2;
  string sqrtPriceX96 = 3;
  string liquidity = 4;
  int32 tick = 5;
}
